"use strict";
var __extends = (this && this.__extends) || (function () {
    var extendStatics = function (d, b) {
        extendStatics = Object.setPrototypeOf ||
            ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
            function (d, b) { for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p]; };
        return extendStatics(d, b);
    };
    return function (d, b) {
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
var __assign = (this && this.__assign) || function () {
    __assign = Object.assign || function(t) {
        for (var s, i = 1, n = arguments.length; i < n; i++) {
            s = arguments[i];
            for (var p in s) if (Object.prototype.hasOwnProperty.call(s, p))
                t[p] = s[p];
        }
        return t;
    };
    return __assign.apply(this, arguments);
};
var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
    function adopt(value) { return value instanceof P ? value : new P(function (resolve) { resolve(value); }); }
    return new (P || (P = Promise))(function (resolve, reject) {
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
        function rejected(value) { try { step(generator["throw"](value)); } catch (e) { reject(e); } }
        function step(result) { result.done ? resolve(result.value) : adopt(result.value).then(fulfilled, rejected); }
        step((generator = generator.apply(thisArg, _arguments || [])).next());
    });
};
var __generator = (this && this.__generator) || function (thisArg, body) {
    var _ = { label: 0, sent: function() { if (t[0] & 1) throw t[1]; return t[1]; }, trys: [], ops: [] }, f, y, t, g;
    return g = { next: verb(0), "throw": verb(1), "return": verb(2) }, typeof Symbol === "function" && (g[Symbol.iterator] = function() { return this; }), g;
    function verb(n) { return function (v) { return step([n, v]); }; }
    function step(op) {
        if (f) throw new TypeError("Generator is already executing.");
        while (_) try {
            if (f = 1, y && (t = op[0] & 2 ? y["return"] : op[0] ? y["throw"] || ((t = y["return"]) && t.call(y), 0) : y.next) && !(t = t.call(y, op[1])).done) return t;
            if (y = 0, t) op = [op[0] & 2, t.value];
            switch (op[0]) {
                case 0: case 1: t = op; break;
                case 4: _.label++; return { value: op[1], done: false };
                case 5: _.label++; y = op[1]; op = [0]; continue;
                case 7: op = _.ops.pop(); _.trys.pop(); continue;
                default:
                    if (!(t = _.trys, t = t.length > 0 && t[t.length - 1]) && (op[0] === 6 || op[0] === 2)) { _ = 0; continue; }
                    if (op[0] === 3 && (!t || (op[1] > t[0] && op[1] < t[3]))) { _.label = op[1]; break; }
                    if (op[0] === 6 && _.label < t[1]) { _.label = t[1]; t = op; break; }
                    if (t && _.label < t[2]) { _.label = t[2]; _.ops.push(op); break; }
                    if (t[2]) _.ops.pop();
                    _.trys.pop(); continue;
            }
            op = body.call(thisArg, _);
        } catch (e) { op = [6, e]; y = 0; } finally { f = t = 0; }
        if (op[0] & 5) throw op[1]; return { value: op[0] ? op[1] : void 0, done: true };
    }
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.ModelsApi = exports.ModelsApiFactory = exports.ModelsApiFp = exports.ModelsApiAxiosParamCreator = void 0;
/* tslint:disable */
/* eslint-disable */
/**
 * Ilyde Apis
 * OpenApi interface which exposes Ilyde resources to frontends
 *
 * OpenAPI spec version: 0.2.0
 * Contact: alessiofiorentino@hopenly.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
var axios_1 = require("axios");
// Some imports not used depending on template conditions
// @ts-ignore
var base_1 = require("../base");
/**
 * ModelsApi - axios parameter creator
 * @export
 */
exports.ModelsApiAxiosParamCreator = function (configuration) {
    var _this = this;
    return {
        /**
         *
         * @summary Create a model
         * @param {Model} body Request payload to create a model
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createModel: function (body, options) {
            if (options === void 0) { options = {}; }
            return __awaiter(_this, void 0, void 0, function () {
                var localVarPath, localVarUrlObj, baseOptions, localVarRequestOptions, localVarHeaderParameter, localVarQueryParameter, query, key, key, headersFromBaseOptions, needsSerialization;
                return __generator(this, function (_a) {
                    // verify required parameter 'body' is not null or undefined
                    if (body === null || body === undefined) {
                        throw new base_1.RequiredError('body', 'Required parameter body was null or undefined when calling createModel.');
                    }
                    localVarPath = "/models";
                    localVarUrlObj = new URL(localVarPath, 'https://example.com');
                    if (configuration) {
                        baseOptions = configuration.baseOptions;
                    }
                    localVarRequestOptions = __assign(__assign({ method: 'POST' }, baseOptions), options);
                    localVarHeaderParameter = {};
                    localVarQueryParameter = {};
                    // authentication jwt required
                    localVarHeaderParameter['Content-Type'] = 'application/json';
                    query = new URLSearchParams(localVarUrlObj.search);
                    for (key in localVarQueryParameter) {
                        query.set(key, localVarQueryParameter[key]);
                    }
                    for (key in options.query) {
                        query.set(key, options.query[key]);
                    }
                    localVarUrlObj.search = (new URLSearchParams(query)).toString();
                    headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
                    localVarRequestOptions.headers = __assign(__assign(__assign({}, localVarHeaderParameter), headersFromBaseOptions), options.headers);
                    needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
                    localVarRequestOptions.data = needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");
                    return [2 /*return*/, {
                            url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                            options: localVarRequestOptions,
                        }];
                });
            });
        },
        /**
         *
         * @summary Create a model version
         * @param {ModelVersion} body Request payload to create a model version
         * @param {string} name The unique name of the model
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createModelVersion: function (body, name, options) {
            if (options === void 0) { options = {}; }
            return __awaiter(_this, void 0, void 0, function () {
                var localVarPath, localVarUrlObj, baseOptions, localVarRequestOptions, localVarHeaderParameter, localVarQueryParameter, query, key, key, headersFromBaseOptions, needsSerialization;
                return __generator(this, function (_a) {
                    // verify required parameter 'body' is not null or undefined
                    if (body === null || body === undefined) {
                        throw new base_1.RequiredError('body', 'Required parameter body was null or undefined when calling createModelVersion.');
                    }
                    // verify required parameter 'name' is not null or undefined
                    if (name === null || name === undefined) {
                        throw new base_1.RequiredError('name', 'Required parameter name was null or undefined when calling createModelVersion.');
                    }
                    localVarPath = "/model-versions/create";
                    localVarUrlObj = new URL(localVarPath, 'https://example.com');
                    if (configuration) {
                        baseOptions = configuration.baseOptions;
                    }
                    localVarRequestOptions = __assign(__assign({ method: 'POST' }, baseOptions), options);
                    localVarHeaderParameter = {};
                    localVarQueryParameter = {};
                    // authentication jwt required
                    if (name !== undefined) {
                        localVarQueryParameter['name'] = name;
                    }
                    localVarHeaderParameter['Content-Type'] = 'application/json';
                    query = new URLSearchParams(localVarUrlObj.search);
                    for (key in localVarQueryParameter) {
                        query.set(key, localVarQueryParameter[key]);
                    }
                    for (key in options.query) {
                        query.set(key, options.query[key]);
                    }
                    localVarUrlObj.search = (new URLSearchParams(query)).toString();
                    headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
                    localVarRequestOptions.headers = __assign(__assign(__assign({}, localVarHeaderParameter), headersFromBaseOptions), options.headers);
                    needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
                    localVarRequestOptions.data = needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");
                    return [2 /*return*/, {
                            url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                            options: localVarRequestOptions,
                        }];
                });
            });
        },
        /**
         *
         * @summary Delete a model
         * @param {string} name The unique name of the model
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteModel: function (name, options) {
            if (options === void 0) { options = {}; }
            return __awaiter(_this, void 0, void 0, function () {
                var localVarPath, localVarUrlObj, baseOptions, localVarRequestOptions, localVarHeaderParameter, localVarQueryParameter, query, key, key, headersFromBaseOptions;
                return __generator(this, function (_a) {
                    // verify required parameter 'name' is not null or undefined
                    if (name === null || name === undefined) {
                        throw new base_1.RequiredError('name', 'Required parameter name was null or undefined when calling deleteModel.');
                    }
                    localVarPath = "/models/delete";
                    localVarUrlObj = new URL(localVarPath, 'https://example.com');
                    if (configuration) {
                        baseOptions = configuration.baseOptions;
                    }
                    localVarRequestOptions = __assign(__assign({ method: 'DELETE' }, baseOptions), options);
                    localVarHeaderParameter = {};
                    localVarQueryParameter = {};
                    // authentication jwt required
                    if (name !== undefined) {
                        localVarQueryParameter['name'] = name;
                    }
                    query = new URLSearchParams(localVarUrlObj.search);
                    for (key in localVarQueryParameter) {
                        query.set(key, localVarQueryParameter[key]);
                    }
                    for (key in options.query) {
                        query.set(key, options.query[key]);
                    }
                    localVarUrlObj.search = (new URLSearchParams(query)).toString();
                    headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
                    localVarRequestOptions.headers = __assign(__assign(__assign({}, localVarHeaderParameter), headersFromBaseOptions), options.headers);
                    return [2 /*return*/, {
                            url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                            options: localVarRequestOptions,
                        }];
                });
            });
        },
        /**
         *
         * @summary delete a model version
         * @param {string} name The unique name of the model
         * @param {string} version The version of the model to delete
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteModelVersion: function (name, version, options) {
            if (options === void 0) { options = {}; }
            return __awaiter(_this, void 0, void 0, function () {
                var localVarPath, localVarUrlObj, baseOptions, localVarRequestOptions, localVarHeaderParameter, localVarQueryParameter, query, key, key, headersFromBaseOptions;
                return __generator(this, function (_a) {
                    // verify required parameter 'name' is not null or undefined
                    if (name === null || name === undefined) {
                        throw new base_1.RequiredError('name', 'Required parameter name was null or undefined when calling deleteModelVersion.');
                    }
                    // verify required parameter 'version' is not null or undefined
                    if (version === null || version === undefined) {
                        throw new base_1.RequiredError('version', 'Required parameter version was null or undefined when calling deleteModelVersion.');
                    }
                    localVarPath = "/model-versions/delete";
                    localVarUrlObj = new URL(localVarPath, 'https://example.com');
                    if (configuration) {
                        baseOptions = configuration.baseOptions;
                    }
                    localVarRequestOptions = __assign(__assign({ method: 'DELETE' }, baseOptions), options);
                    localVarHeaderParameter = {};
                    localVarQueryParameter = {};
                    // authentication jwt required
                    if (name !== undefined) {
                        localVarQueryParameter['name'] = name;
                    }
                    if (version !== undefined) {
                        localVarQueryParameter['version'] = version;
                    }
                    query = new URLSearchParams(localVarUrlObj.search);
                    for (key in localVarQueryParameter) {
                        query.set(key, localVarQueryParameter[key]);
                    }
                    for (key in options.query) {
                        query.set(key, options.query[key]);
                    }
                    localVarUrlObj.search = (new URLSearchParams(query)).toString();
                    headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
                    localVarRequestOptions.headers = __assign(__assign(__assign({}, localVarHeaderParameter), headersFromBaseOptions), options.headers);
                    return [2 /*return*/, {
                            url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                            options: localVarRequestOptions,
                        }];
                });
            });
        },
        /**
         *
         * @summary get a model version
         * @param {string} name The unique name of the model
         * @param {string} version The version of the model to retrieve
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getModelVersion: function (name, version, options) {
            if (options === void 0) { options = {}; }
            return __awaiter(_this, void 0, void 0, function () {
                var localVarPath, localVarUrlObj, baseOptions, localVarRequestOptions, localVarHeaderParameter, localVarQueryParameter, query, key, key, headersFromBaseOptions;
                return __generator(this, function (_a) {
                    // verify required parameter 'name' is not null or undefined
                    if (name === null || name === undefined) {
                        throw new base_1.RequiredError('name', 'Required parameter name was null or undefined when calling getModelVersion.');
                    }
                    // verify required parameter 'version' is not null or undefined
                    if (version === null || version === undefined) {
                        throw new base_1.RequiredError('version', 'Required parameter version was null or undefined when calling getModelVersion.');
                    }
                    localVarPath = "/model-versions/get";
                    localVarUrlObj = new URL(localVarPath, 'https://example.com');
                    if (configuration) {
                        baseOptions = configuration.baseOptions;
                    }
                    localVarRequestOptions = __assign(__assign({ method: 'GET' }, baseOptions), options);
                    localVarHeaderParameter = {};
                    localVarQueryParameter = {};
                    // authentication jwt required
                    if (name !== undefined) {
                        localVarQueryParameter['name'] = name;
                    }
                    if (version !== undefined) {
                        localVarQueryParameter['version'] = version;
                    }
                    query = new URLSearchParams(localVarUrlObj.search);
                    for (key in localVarQueryParameter) {
                        query.set(key, localVarQueryParameter[key]);
                    }
                    for (key in options.query) {
                        query.set(key, options.query[key]);
                    }
                    localVarUrlObj.search = (new URLSearchParams(query)).toString();
                    headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
                    localVarRequestOptions.headers = __assign(__assign(__assign({}, localVarHeaderParameter), headersFromBaseOptions), options.headers);
                    return [2 /*return*/, {
                            url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                            options: localVarRequestOptions,
                        }];
                });
            });
        },
        /**
         *
         * @summary list versions of a model
         * @param {string} name The unique name of the model
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listModelVersions: function (name, options) {
            if (options === void 0) { options = {}; }
            return __awaiter(_this, void 0, void 0, function () {
                var localVarPath, localVarUrlObj, baseOptions, localVarRequestOptions, localVarHeaderParameter, localVarQueryParameter, query, key, key, headersFromBaseOptions;
                return __generator(this, function (_a) {
                    // verify required parameter 'name' is not null or undefined
                    if (name === null || name === undefined) {
                        throw new base_1.RequiredError('name', 'Required parameter name was null or undefined when calling listModelVersions.');
                    }
                    localVarPath = "/model-versions/list";
                    localVarUrlObj = new URL(localVarPath, 'https://example.com');
                    if (configuration) {
                        baseOptions = configuration.baseOptions;
                    }
                    localVarRequestOptions = __assign(__assign({ method: 'GET' }, baseOptions), options);
                    localVarHeaderParameter = {};
                    localVarQueryParameter = {};
                    // authentication jwt required
                    if (name !== undefined) {
                        localVarQueryParameter['name'] = name;
                    }
                    query = new URLSearchParams(localVarUrlObj.search);
                    for (key in localVarQueryParameter) {
                        query.set(key, localVarQueryParameter[key]);
                    }
                    for (key in options.query) {
                        query.set(key, options.query[key]);
                    }
                    localVarUrlObj.search = (new URLSearchParams(query)).toString();
                    headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
                    localVarRequestOptions.headers = __assign(__assign(__assign({}, localVarHeaderParameter), headersFromBaseOptions), options.headers);
                    return [2 /*return*/, {
                            url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                            options: localVarRequestOptions,
                        }];
                });
            });
        },
        /**
         *
         * @summary Retrieve a model
         * @param {string} name The unique name of the model
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        retrieveModel: function (name, options) {
            if (options === void 0) { options = {}; }
            return __awaiter(_this, void 0, void 0, function () {
                var localVarPath, localVarUrlObj, baseOptions, localVarRequestOptions, localVarHeaderParameter, localVarQueryParameter, query, key, key, headersFromBaseOptions;
                return __generator(this, function (_a) {
                    // verify required parameter 'name' is not null or undefined
                    if (name === null || name === undefined) {
                        throw new base_1.RequiredError('name', 'Required parameter name was null or undefined when calling retrieveModel.');
                    }
                    localVarPath = "/models/get";
                    localVarUrlObj = new URL(localVarPath, 'https://example.com');
                    if (configuration) {
                        baseOptions = configuration.baseOptions;
                    }
                    localVarRequestOptions = __assign(__assign({ method: 'GET' }, baseOptions), options);
                    localVarHeaderParameter = {};
                    localVarQueryParameter = {};
                    // authentication jwt required
                    if (name !== undefined) {
                        localVarQueryParameter['name'] = name;
                    }
                    query = new URLSearchParams(localVarUrlObj.search);
                    for (key in localVarQueryParameter) {
                        query.set(key, localVarQueryParameter[key]);
                    }
                    for (key in options.query) {
                        query.set(key, options.query[key]);
                    }
                    localVarUrlObj.search = (new URLSearchParams(query)).toString();
                    headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
                    localVarRequestOptions.headers = __assign(__assign(__assign({}, localVarHeaderParameter), headersFromBaseOptions), options.headers);
                    return [2 /*return*/, {
                            url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                            options: localVarRequestOptions,
                        }];
                });
            });
        },
        /**
         *
         * @summary Transition model version stage
         * @param {Body4} body
         * @param {string} name The unique name of the model
         * @param {string} version The version of the model
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        transitionModelVersionStage: function (body, name, version, options) {
            if (options === void 0) { options = {}; }
            return __awaiter(_this, void 0, void 0, function () {
                var localVarPath, localVarUrlObj, baseOptions, localVarRequestOptions, localVarHeaderParameter, localVarQueryParameter, query, key, key, headersFromBaseOptions, needsSerialization;
                return __generator(this, function (_a) {
                    // verify required parameter 'body' is not null or undefined
                    if (body === null || body === undefined) {
                        throw new base_1.RequiredError('body', 'Required parameter body was null or undefined when calling transitionModelVersionStage.');
                    }
                    // verify required parameter 'name' is not null or undefined
                    if (name === null || name === undefined) {
                        throw new base_1.RequiredError('name', 'Required parameter name was null or undefined when calling transitionModelVersionStage.');
                    }
                    // verify required parameter 'version' is not null or undefined
                    if (version === null || version === undefined) {
                        throw new base_1.RequiredError('version', 'Required parameter version was null or undefined when calling transitionModelVersionStage.');
                    }
                    localVarPath = "/model-versions/transition-stage";
                    localVarUrlObj = new URL(localVarPath, 'https://example.com');
                    if (configuration) {
                        baseOptions = configuration.baseOptions;
                    }
                    localVarRequestOptions = __assign(__assign({ method: 'PATCH' }, baseOptions), options);
                    localVarHeaderParameter = {};
                    localVarQueryParameter = {};
                    // authentication jwt required
                    if (name !== undefined) {
                        localVarQueryParameter['name'] = name;
                    }
                    if (version !== undefined) {
                        localVarQueryParameter['version'] = version;
                    }
                    localVarHeaderParameter['Content-Type'] = 'application/json';
                    query = new URLSearchParams(localVarUrlObj.search);
                    for (key in localVarQueryParameter) {
                        query.set(key, localVarQueryParameter[key]);
                    }
                    for (key in options.query) {
                        query.set(key, options.query[key]);
                    }
                    localVarUrlObj.search = (new URLSearchParams(query)).toString();
                    headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
                    localVarRequestOptions.headers = __assign(__assign(__assign({}, localVarHeaderParameter), headersFromBaseOptions), options.headers);
                    needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
                    localVarRequestOptions.data = needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");
                    return [2 /*return*/, {
                            url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                            options: localVarRequestOptions,
                        }];
                });
            });
        },
        /**
         *
         * @summary Update a model
         * @param {Body7} body Model object to update
         * @param {string} name The unique name of the model
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateModel: function (body, name, options) {
            if (options === void 0) { options = {}; }
            return __awaiter(_this, void 0, void 0, function () {
                var localVarPath, localVarUrlObj, baseOptions, localVarRequestOptions, localVarHeaderParameter, localVarQueryParameter, query, key, key, headersFromBaseOptions, needsSerialization;
                return __generator(this, function (_a) {
                    // verify required parameter 'body' is not null or undefined
                    if (body === null || body === undefined) {
                        throw new base_1.RequiredError('body', 'Required parameter body was null or undefined when calling updateModel.');
                    }
                    // verify required parameter 'name' is not null or undefined
                    if (name === null || name === undefined) {
                        throw new base_1.RequiredError('name', 'Required parameter name was null or undefined when calling updateModel.');
                    }
                    localVarPath = "/models/update";
                    localVarUrlObj = new URL(localVarPath, 'https://example.com');
                    if (configuration) {
                        baseOptions = configuration.baseOptions;
                    }
                    localVarRequestOptions = __assign(__assign({ method: 'PATCH' }, baseOptions), options);
                    localVarHeaderParameter = {};
                    localVarQueryParameter = {};
                    // authentication jwt required
                    if (name !== undefined) {
                        localVarQueryParameter['name'] = name;
                    }
                    localVarHeaderParameter['Content-Type'] = 'application/json';
                    query = new URLSearchParams(localVarUrlObj.search);
                    for (key in localVarQueryParameter) {
                        query.set(key, localVarQueryParameter[key]);
                    }
                    for (key in options.query) {
                        query.set(key, options.query[key]);
                    }
                    localVarUrlObj.search = (new URLSearchParams(query)).toString();
                    headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
                    localVarRequestOptions.headers = __assign(__assign(__assign({}, localVarHeaderParameter), headersFromBaseOptions), options.headers);
                    needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
                    localVarRequestOptions.data = needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");
                    return [2 /*return*/, {
                            url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                            options: localVarRequestOptions,
                        }];
                });
            });
        },
        /**
         *
         * @summary update a model version
         * @param {Body5} body
         * @param {string} name The unique name of the model
         * @param {string} version The version of the model to retrieve
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateModelVersion: function (body, name, version, options) {
            if (options === void 0) { options = {}; }
            return __awaiter(_this, void 0, void 0, function () {
                var localVarPath, localVarUrlObj, baseOptions, localVarRequestOptions, localVarHeaderParameter, localVarQueryParameter, query, key, key, headersFromBaseOptions, needsSerialization;
                return __generator(this, function (_a) {
                    // verify required parameter 'body' is not null or undefined
                    if (body === null || body === undefined) {
                        throw new base_1.RequiredError('body', 'Required parameter body was null or undefined when calling updateModelVersion.');
                    }
                    // verify required parameter 'name' is not null or undefined
                    if (name === null || name === undefined) {
                        throw new base_1.RequiredError('name', 'Required parameter name was null or undefined when calling updateModelVersion.');
                    }
                    // verify required parameter 'version' is not null or undefined
                    if (version === null || version === undefined) {
                        throw new base_1.RequiredError('version', 'Required parameter version was null or undefined when calling updateModelVersion.');
                    }
                    localVarPath = "/model-versions/update";
                    localVarUrlObj = new URL(localVarPath, 'https://example.com');
                    if (configuration) {
                        baseOptions = configuration.baseOptions;
                    }
                    localVarRequestOptions = __assign(__assign({ method: 'PATCH' }, baseOptions), options);
                    localVarHeaderParameter = {};
                    localVarQueryParameter = {};
                    // authentication jwt required
                    if (name !== undefined) {
                        localVarQueryParameter['name'] = name;
                    }
                    if (version !== undefined) {
                        localVarQueryParameter['version'] = version;
                    }
                    localVarHeaderParameter['Content-Type'] = 'application/json';
                    query = new URLSearchParams(localVarUrlObj.search);
                    for (key in localVarQueryParameter) {
                        query.set(key, localVarQueryParameter[key]);
                    }
                    for (key in options.query) {
                        query.set(key, options.query[key]);
                    }
                    localVarUrlObj.search = (new URLSearchParams(query)).toString();
                    headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
                    localVarRequestOptions.headers = __assign(__assign(__assign({}, localVarHeaderParameter), headersFromBaseOptions), options.headers);
                    needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
                    localVarRequestOptions.data = needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");
                    return [2 /*return*/, {
                            url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                            options: localVarRequestOptions,
                        }];
                });
            });
        },
    };
};
/**
 * ModelsApi - functional programming interface
 * @export
 */
exports.ModelsApiFp = function (configuration) {
    return {
        /**
         *
         * @summary Create a model
         * @param {Model} body Request payload to create a model
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createModel: function (body, options) {
            return __awaiter(this, void 0, void 0, function () {
                var localVarAxiosArgs;
                return __generator(this, function (_a) {
                    switch (_a.label) {
                        case 0: return [4 /*yield*/, exports.ModelsApiAxiosParamCreator(configuration).createModel(body, options)];
                        case 1:
                            localVarAxiosArgs = _a.sent();
                            return [2 /*return*/, function (axios, basePath) {
                                    if (axios === void 0) { axios = axios_1.default; }
                                    if (basePath === void 0) { basePath = base_1.BASE_PATH; }
                                    var axiosRequestArgs = __assign(__assign({}, localVarAxiosArgs.options), { url: basePath + localVarAxiosArgs.url });
                                    return axios.request(axiosRequestArgs);
                                }];
                    }
                });
            });
        },
        /**
         *
         * @summary Create a model version
         * @param {ModelVersion} body Request payload to create a model version
         * @param {string} name The unique name of the model
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createModelVersion: function (body, name, options) {
            return __awaiter(this, void 0, void 0, function () {
                var localVarAxiosArgs;
                return __generator(this, function (_a) {
                    switch (_a.label) {
                        case 0: return [4 /*yield*/, exports.ModelsApiAxiosParamCreator(configuration).createModelVersion(body, name, options)];
                        case 1:
                            localVarAxiosArgs = _a.sent();
                            return [2 /*return*/, function (axios, basePath) {
                                    if (axios === void 0) { axios = axios_1.default; }
                                    if (basePath === void 0) { basePath = base_1.BASE_PATH; }
                                    var axiosRequestArgs = __assign(__assign({}, localVarAxiosArgs.options), { url: basePath + localVarAxiosArgs.url });
                                    return axios.request(axiosRequestArgs);
                                }];
                    }
                });
            });
        },
        /**
         *
         * @summary Delete a model
         * @param {string} name The unique name of the model
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteModel: function (name, options) {
            return __awaiter(this, void 0, void 0, function () {
                var localVarAxiosArgs;
                return __generator(this, function (_a) {
                    switch (_a.label) {
                        case 0: return [4 /*yield*/, exports.ModelsApiAxiosParamCreator(configuration).deleteModel(name, options)];
                        case 1:
                            localVarAxiosArgs = _a.sent();
                            return [2 /*return*/, function (axios, basePath) {
                                    if (axios === void 0) { axios = axios_1.default; }
                                    if (basePath === void 0) { basePath = base_1.BASE_PATH; }
                                    var axiosRequestArgs = __assign(__assign({}, localVarAxiosArgs.options), { url: basePath + localVarAxiosArgs.url });
                                    return axios.request(axiosRequestArgs);
                                }];
                    }
                });
            });
        },
        /**
         *
         * @summary delete a model version
         * @param {string} name The unique name of the model
         * @param {string} version The version of the model to delete
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteModelVersion: function (name, version, options) {
            return __awaiter(this, void 0, void 0, function () {
                var localVarAxiosArgs;
                return __generator(this, function (_a) {
                    switch (_a.label) {
                        case 0: return [4 /*yield*/, exports.ModelsApiAxiosParamCreator(configuration).deleteModelVersion(name, version, options)];
                        case 1:
                            localVarAxiosArgs = _a.sent();
                            return [2 /*return*/, function (axios, basePath) {
                                    if (axios === void 0) { axios = axios_1.default; }
                                    if (basePath === void 0) { basePath = base_1.BASE_PATH; }
                                    var axiosRequestArgs = __assign(__assign({}, localVarAxiosArgs.options), { url: basePath + localVarAxiosArgs.url });
                                    return axios.request(axiosRequestArgs);
                                }];
                    }
                });
            });
        },
        /**
         *
         * @summary get a model version
         * @param {string} name The unique name of the model
         * @param {string} version The version of the model to retrieve
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getModelVersion: function (name, version, options) {
            return __awaiter(this, void 0, void 0, function () {
                var localVarAxiosArgs;
                return __generator(this, function (_a) {
                    switch (_a.label) {
                        case 0: return [4 /*yield*/, exports.ModelsApiAxiosParamCreator(configuration).getModelVersion(name, version, options)];
                        case 1:
                            localVarAxiosArgs = _a.sent();
                            return [2 /*return*/, function (axios, basePath) {
                                    if (axios === void 0) { axios = axios_1.default; }
                                    if (basePath === void 0) { basePath = base_1.BASE_PATH; }
                                    var axiosRequestArgs = __assign(__assign({}, localVarAxiosArgs.options), { url: basePath + localVarAxiosArgs.url });
                                    return axios.request(axiosRequestArgs);
                                }];
                    }
                });
            });
        },
        /**
         *
         * @summary list versions of a model
         * @param {string} name The unique name of the model
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listModelVersions: function (name, options) {
            return __awaiter(this, void 0, void 0, function () {
                var localVarAxiosArgs;
                return __generator(this, function (_a) {
                    switch (_a.label) {
                        case 0: return [4 /*yield*/, exports.ModelsApiAxiosParamCreator(configuration).listModelVersions(name, options)];
                        case 1:
                            localVarAxiosArgs = _a.sent();
                            return [2 /*return*/, function (axios, basePath) {
                                    if (axios === void 0) { axios = axios_1.default; }
                                    if (basePath === void 0) { basePath = base_1.BASE_PATH; }
                                    var axiosRequestArgs = __assign(__assign({}, localVarAxiosArgs.options), { url: basePath + localVarAxiosArgs.url });
                                    return axios.request(axiosRequestArgs);
                                }];
                    }
                });
            });
        },
        /**
         *
         * @summary Retrieve a model
         * @param {string} name The unique name of the model
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        retrieveModel: function (name, options) {
            return __awaiter(this, void 0, void 0, function () {
                var localVarAxiosArgs;
                return __generator(this, function (_a) {
                    switch (_a.label) {
                        case 0: return [4 /*yield*/, exports.ModelsApiAxiosParamCreator(configuration).retrieveModel(name, options)];
                        case 1:
                            localVarAxiosArgs = _a.sent();
                            return [2 /*return*/, function (axios, basePath) {
                                    if (axios === void 0) { axios = axios_1.default; }
                                    if (basePath === void 0) { basePath = base_1.BASE_PATH; }
                                    var axiosRequestArgs = __assign(__assign({}, localVarAxiosArgs.options), { url: basePath + localVarAxiosArgs.url });
                                    return axios.request(axiosRequestArgs);
                                }];
                    }
                });
            });
        },
        /**
         *
         * @summary Transition model version stage
         * @param {Body4} body
         * @param {string} name The unique name of the model
         * @param {string} version The version of the model
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        transitionModelVersionStage: function (body, name, version, options) {
            return __awaiter(this, void 0, void 0, function () {
                var localVarAxiosArgs;
                return __generator(this, function (_a) {
                    switch (_a.label) {
                        case 0: return [4 /*yield*/, exports.ModelsApiAxiosParamCreator(configuration).transitionModelVersionStage(body, name, version, options)];
                        case 1:
                            localVarAxiosArgs = _a.sent();
                            return [2 /*return*/, function (axios, basePath) {
                                    if (axios === void 0) { axios = axios_1.default; }
                                    if (basePath === void 0) { basePath = base_1.BASE_PATH; }
                                    var axiosRequestArgs = __assign(__assign({}, localVarAxiosArgs.options), { url: basePath + localVarAxiosArgs.url });
                                    return axios.request(axiosRequestArgs);
                                }];
                    }
                });
            });
        },
        /**
         *
         * @summary Update a model
         * @param {Body7} body Model object to update
         * @param {string} name The unique name of the model
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateModel: function (body, name, options) {
            return __awaiter(this, void 0, void 0, function () {
                var localVarAxiosArgs;
                return __generator(this, function (_a) {
                    switch (_a.label) {
                        case 0: return [4 /*yield*/, exports.ModelsApiAxiosParamCreator(configuration).updateModel(body, name, options)];
                        case 1:
                            localVarAxiosArgs = _a.sent();
                            return [2 /*return*/, function (axios, basePath) {
                                    if (axios === void 0) { axios = axios_1.default; }
                                    if (basePath === void 0) { basePath = base_1.BASE_PATH; }
                                    var axiosRequestArgs = __assign(__assign({}, localVarAxiosArgs.options), { url: basePath + localVarAxiosArgs.url });
                                    return axios.request(axiosRequestArgs);
                                }];
                    }
                });
            });
        },
        /**
         *
         * @summary update a model version
         * @param {Body5} body
         * @param {string} name The unique name of the model
         * @param {string} version The version of the model to retrieve
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateModelVersion: function (body, name, version, options) {
            return __awaiter(this, void 0, void 0, function () {
                var localVarAxiosArgs;
                return __generator(this, function (_a) {
                    switch (_a.label) {
                        case 0: return [4 /*yield*/, exports.ModelsApiAxiosParamCreator(configuration).updateModelVersion(body, name, version, options)];
                        case 1:
                            localVarAxiosArgs = _a.sent();
                            return [2 /*return*/, function (axios, basePath) {
                                    if (axios === void 0) { axios = axios_1.default; }
                                    if (basePath === void 0) { basePath = base_1.BASE_PATH; }
                                    var axiosRequestArgs = __assign(__assign({}, localVarAxiosArgs.options), { url: basePath + localVarAxiosArgs.url });
                                    return axios.request(axiosRequestArgs);
                                }];
                    }
                });
            });
        },
    };
};
/**
 * ModelsApi - factory interface
 * @export
 */
exports.ModelsApiFactory = function (configuration, basePath, axios) {
    return {
        /**
         *
         * @summary Create a model
         * @param {Model} body Request payload to create a model
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createModel: function (body, options) {
            return exports.ModelsApiFp(configuration).createModel(body, options).then(function (request) { return request(axios, basePath); });
        },
        /**
         *
         * @summary Create a model version
         * @param {ModelVersion} body Request payload to create a model version
         * @param {string} name The unique name of the model
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createModelVersion: function (body, name, options) {
            return exports.ModelsApiFp(configuration).createModelVersion(body, name, options).then(function (request) { return request(axios, basePath); });
        },
        /**
         *
         * @summary Delete a model
         * @param {string} name The unique name of the model
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteModel: function (name, options) {
            return exports.ModelsApiFp(configuration).deleteModel(name, options).then(function (request) { return request(axios, basePath); });
        },
        /**
         *
         * @summary delete a model version
         * @param {string} name The unique name of the model
         * @param {string} version The version of the model to delete
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteModelVersion: function (name, version, options) {
            return exports.ModelsApiFp(configuration).deleteModelVersion(name, version, options).then(function (request) { return request(axios, basePath); });
        },
        /**
         *
         * @summary get a model version
         * @param {string} name The unique name of the model
         * @param {string} version The version of the model to retrieve
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getModelVersion: function (name, version, options) {
            return exports.ModelsApiFp(configuration).getModelVersion(name, version, options).then(function (request) { return request(axios, basePath); });
        },
        /**
         *
         * @summary list versions of a model
         * @param {string} name The unique name of the model
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listModelVersions: function (name, options) {
            return exports.ModelsApiFp(configuration).listModelVersions(name, options).then(function (request) { return request(axios, basePath); });
        },
        /**
         *
         * @summary Retrieve a model
         * @param {string} name The unique name of the model
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        retrieveModel: function (name, options) {
            return exports.ModelsApiFp(configuration).retrieveModel(name, options).then(function (request) { return request(axios, basePath); });
        },
        /**
         *
         * @summary Transition model version stage
         * @param {Body4} body
         * @param {string} name The unique name of the model
         * @param {string} version The version of the model
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        transitionModelVersionStage: function (body, name, version, options) {
            return exports.ModelsApiFp(configuration).transitionModelVersionStage(body, name, version, options).then(function (request) { return request(axios, basePath); });
        },
        /**
         *
         * @summary Update a model
         * @param {Body7} body Model object to update
         * @param {string} name The unique name of the model
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateModel: function (body, name, options) {
            return exports.ModelsApiFp(configuration).updateModel(body, name, options).then(function (request) { return request(axios, basePath); });
        },
        /**
         *
         * @summary update a model version
         * @param {Body5} body
         * @param {string} name The unique name of the model
         * @param {string} version The version of the model to retrieve
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateModelVersion: function (body, name, version, options) {
            return exports.ModelsApiFp(configuration).updateModelVersion(body, name, version, options).then(function (request) { return request(axios, basePath); });
        },
    };
};
/**
 * ModelsApi - object-oriented interface
 * @export
 * @class ModelsApi
 * @extends {BaseAPI}
 */
var ModelsApi = /** @class */ (function (_super) {
    __extends(ModelsApi, _super);
    function ModelsApi() {
        return _super !== null && _super.apply(this, arguments) || this;
    }
    /**
     *
     * @summary Create a model
     * @param {Model} body Request payload to create a model
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ModelsApi
     */
    ModelsApi.prototype.createModel = function (body, options) {
        var _this = this;
        return exports.ModelsApiFp(this.configuration).createModel(body, options).then(function (request) { return request(_this.axios, _this.basePath); });
    };
    /**
     *
     * @summary Create a model version
     * @param {ModelVersion} body Request payload to create a model version
     * @param {string} name The unique name of the model
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ModelsApi
     */
    ModelsApi.prototype.createModelVersion = function (body, name, options) {
        var _this = this;
        return exports.ModelsApiFp(this.configuration).createModelVersion(body, name, options).then(function (request) { return request(_this.axios, _this.basePath); });
    };
    /**
     *
     * @summary Delete a model
     * @param {string} name The unique name of the model
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ModelsApi
     */
    ModelsApi.prototype.deleteModel = function (name, options) {
        var _this = this;
        return exports.ModelsApiFp(this.configuration).deleteModel(name, options).then(function (request) { return request(_this.axios, _this.basePath); });
    };
    /**
     *
     * @summary delete a model version
     * @param {string} name The unique name of the model
     * @param {string} version The version of the model to delete
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ModelsApi
     */
    ModelsApi.prototype.deleteModelVersion = function (name, version, options) {
        var _this = this;
        return exports.ModelsApiFp(this.configuration).deleteModelVersion(name, version, options).then(function (request) { return request(_this.axios, _this.basePath); });
    };
    /**
     *
     * @summary get a model version
     * @param {string} name The unique name of the model
     * @param {string} version The version of the model to retrieve
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ModelsApi
     */
    ModelsApi.prototype.getModelVersion = function (name, version, options) {
        var _this = this;
        return exports.ModelsApiFp(this.configuration).getModelVersion(name, version, options).then(function (request) { return request(_this.axios, _this.basePath); });
    };
    /**
     *
     * @summary list versions of a model
     * @param {string} name The unique name of the model
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ModelsApi
     */
    ModelsApi.prototype.listModelVersions = function (name, options) {
        var _this = this;
        return exports.ModelsApiFp(this.configuration).listModelVersions(name, options).then(function (request) { return request(_this.axios, _this.basePath); });
    };
    /**
     *
     * @summary Retrieve a model
     * @param {string} name The unique name of the model
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ModelsApi
     */
    ModelsApi.prototype.retrieveModel = function (name, options) {
        var _this = this;
        return exports.ModelsApiFp(this.configuration).retrieveModel(name, options).then(function (request) { return request(_this.axios, _this.basePath); });
    };
    /**
     *
     * @summary Transition model version stage
     * @param {Body4} body
     * @param {string} name The unique name of the model
     * @param {string} version The version of the model
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ModelsApi
     */
    ModelsApi.prototype.transitionModelVersionStage = function (body, name, version, options) {
        var _this = this;
        return exports.ModelsApiFp(this.configuration).transitionModelVersionStage(body, name, version, options).then(function (request) { return request(_this.axios, _this.basePath); });
    };
    /**
     *
     * @summary Update a model
     * @param {Body7} body Model object to update
     * @param {string} name The unique name of the model
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ModelsApi
     */
    ModelsApi.prototype.updateModel = function (body, name, options) {
        var _this = this;
        return exports.ModelsApiFp(this.configuration).updateModel(body, name, options).then(function (request) { return request(_this.axios, _this.basePath); });
    };
    /**
     *
     * @summary update a model version
     * @param {Body5} body
     * @param {string} name The unique name of the model
     * @param {string} version The version of the model to retrieve
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ModelsApi
     */
    ModelsApi.prototype.updateModelVersion = function (body, name, version, options) {
        var _this = this;
        return exports.ModelsApiFp(this.configuration).updateModelVersion(body, name, version, options).then(function (request) { return request(_this.axios, _this.basePath); });
    };
    return ModelsApi;
}(base_1.BaseAPI));
exports.ModelsApi = ModelsApi;
