"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    Object.defineProperty(o, k2, { enumerable: true, get: function() { return m[k]; } });
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __exportStar = (this && this.__exportStar) || function(m, exports) {
    for (var p in m) if (p !== "default" && !exports.hasOwnProperty(p)) __createBinding(exports, m, p);
};
Object.defineProperty(exports, "__esModule", { value: true });
/* tslint:disable */
/* eslint-disable */
/**
 * Ilyde Apis
 * OpenApi interface which exposes Ilyde resources to frontends
 *
 * OpenAPI spec version: 0.2.0
 * Contact: alessiofiorentino@hopenly.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */ __exportStar(require("./apis/datasets-api"), exports);
__exportStar(require("./apis/environments-api"), exports);
__exportStar(require("./apis/experiments-api"), exports);
__exportStar(require("./apis/files-api"), exports);
__exportStar(require("./apis/modelapis-api"), exports);
__exportStar(require("./apis/models-api"), exports);
__exportStar(require("./apis/projects-api"), exports);
__exportStar(require("./apis/runs-api"), exports);
__exportStar(require("./apis/users-api"), exports);
__exportStar(require("./apis/workspaces-api"), exports);
