/**
 * Ilyde Apis
 * OpenApi interface which exposes Ilyde resources to frontends
 *
 * OpenAPI spec version: 0.2.0
 * Contact: alessiofiorentino@hopenly.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface Body4
 */
export interface Body4 {
    /**
     *
     * @type {string}
     * @memberof Body4
     */
    stage: Body4StageEnum;
}
/**
    * @export
    * @enum {string}
    */
export declare enum Body4StageEnum {
    None = "None",
    Staging = "Staging",
    Production = "Production",
    Archived = "Archived"
}
