/**
 * Ilyde Apis
 * OpenApi interface which exposes Ilyde resources to frontends
 *
 * OpenAPI spec version: 0.2.0
 * Contact: alessiofiorentino@hopenly.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface Body2
 */
export interface Body2 {
    /**
     *
     * @type {DatasetslistQuery}
     * @memberof Body2
     */
    query: any;
    /**
     *
     * @type {number}
     * @memberof Body2
     */
    page?: any;
    /**
     *
     * @type {number}
     * @memberof Body2
     */
    limit?: any;
}
