/**
 * Ilyde Apis
 * OpenApi interface which exposes Ilyde resources to frontends
 *
 * OpenAPI spec version: 0.2.0
 * Contact: alessiofiorentino@hopenly.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface DatasetslistQuery
 */
export interface DatasetslistQuery {
    /**
     *
     * @type {string}
     * @memberof DatasetslistQuery
     */
    scope: DatasetslistQueryScopeEnum;
    /**
     *
     * @type {string}
     * @memberof DatasetslistQuery
     */
    project?: any;
}
/**
    * @export
    * @enum {string}
    */
export declare enum DatasetslistQueryScopeEnum {
    Local = "Local",
    Global = "Global"
}
