/**
 * Ilyde Apis
 * OpenApi interface which exposes Ilyde resources to frontends
 *
 * OpenAPI spec version: 0.2.0
 * Contact: alessiofiorentino@hopenly.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface DatasetversionslistQuery
 */
export interface DatasetversionslistQuery {
    /**
     *
     * @type {string}
     * @memberof DatasetversionslistQuery
     */
    id?: any;
    /**
     *
     * @type {string}
     * @memberof DatasetversionslistQuery
     */
    name?: any;
    /**
     *
     * @type {string}
     * @memberof DatasetversionslistQuery
     */
    author?: any;
}
