/**
 * Ilyde Apis
 * OpenApi interface which exposes Ilyde resources to frontends
 *
 * OpenAPI spec version: 0.2.0
 * Contact: alessiofiorentino@hopenly.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface Model
 */
export interface Model {
    /**
     *
     * @type {string}
     * @memberof Model
     */
    name: any;
    /**
     *
     * @type {string}
     * @memberof Model
     */
    description: any;
    /**
     *
     * @type {any}
     * @memberof Model
     */
    tags?: any;
    /**
     *
     * @type {Array&lt;ModelVersion&gt;}
     * @memberof Model
     */
    latestVersions?: any;
    /**
     *
     * @type {number}
     * @memberof Model
     */
    lastUpdatedTimestamp?: any;
    /**
     *
     * @type {number}
     * @memberof Model
     */
    creationTimestamp?: any;
}
