/**
 * Ilyde Apis
 * OpenApi interface which exposes Ilyde resources to frontends
 *
 * OpenAPI spec version: 0.2.0
 * Contact: alessiofiorentino@hopenly.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface ModelApiSpec
 */
export interface ModelApiSpec {
    /**
     *
     * @type {string}
     * @memberof ModelApiSpec
     */
    model: any;
    /**
     *
     * @type {number}
     * @memberof ModelApiSpec
     */
    version: any;
    /**
     *
     * @type {string}
     * @memberof ModelApiSpec
     */
    stage?: any;
    /**
     *
     * @type {string}
     * @memberof ModelApiSpec
     */
    environment: any;
    /**
     *
     * @type {string}
     * @memberof ModelApiSpec
     */
    hardware: any;
}
