/**
 * Ilyde Apis
 * OpenApi interface which exposes Ilyde resources to frontends
 *
 * OpenAPI spec version: 0.2.0
 * Contact: alessiofiorentino@hopenly.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface ModelVersion
 */
export interface ModelVersion {
    /**
     *
     * @type {string}
     * @memberof ModelVersion
     */
    name: any;
    /**
     *
     * @type {string}
     * @memberof ModelVersion
     */
    source: any;
    /**
     *
     * @type {string}
     * @memberof ModelVersion
     */
    description: any;
    /**
     *
     * @type {string}
     * @memberof ModelVersion
     */
    version?: any;
    /**
     *
     * @type {string}
     * @memberof ModelVersion
     */
    currentStage?: any;
    /**
     *
     * @type {string}
     * @memberof ModelVersion
     */
    runId: any;
    /**
     *
     * @type {string}
     * @memberof ModelVersion
     */
    status?: any;
    /**
     *
     * @type {string}
     * @memberof ModelVersion
     */
    statusMessage?: any;
    /**
     *
     * @type {any}
     * @memberof ModelVersion
     */
    tags?: any;
    /**
     *
     * @type {number}
     * @memberof ModelVersion
     */
    lastUpdatedTimestamp?: any;
    /**
     *
     * @type {number}
     * @memberof ModelVersion
     */
    creationTimestamp?: any;
}
