/**
 * Ilyde Apis
 * OpenApi interface which exposes Ilyde resources to frontends
 *
 * OpenAPI spec version: 0.2.0
 * Contact: alessiofiorentino@hopenly.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface PageTokenList
 */
export interface PageTokenList {
    /**
     *
     * @type {string}
     * @memberof PageTokenList
     */
    nextPageToken?: any;
    /**
     *
     * @type {Array&lt;Model | ModelVersion&gt;}
     * @memberof PageTokenList
     */
    data?: any;
}
