/**
 * Ilyde Apis
 * OpenApi interface which exposes Ilyde resources to frontends
 *
 * OpenAPI spec version: 0.2.0
 * Contact: alessiofiorentino@hopenly.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface ProjectRevision
 */
export interface ProjectRevision {
    /**
     *
     * @type {string}
     * @memberof ProjectRevision
     */
    id?: any;
    /**
     *
     * @type {string}
     * @memberof ProjectRevision
     */
    commit: any;
    /**
     *
     * @type {string}
     * @memberof ProjectRevision
     */
    author: any;
    /**
     *
     * @type {string}
     * @memberof ProjectRevision
     */
    project: any;
    /**
     *
     * @type {Array&lt;FileVersion&gt;}
     * @memberof ProjectRevision
     */
    fileTree?: any;
    /**
     *
     * @type {string}
     * @memberof ProjectRevision
     */
    createAt?: any;
}
