/**
 * Ilyde Apis
 * OpenApi interface which exposes Ilyde resources to frontends
 *
 * OpenAPI spec version: 0.2.0
 * Contact: alessiofiorentino@hopenly.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface Project
 */
export interface Project {
    /**
     *
     * @type {string}
     * @memberof Project
     */
    id?: any;
    /**
     *
     * @type {string}
     * @memberof Project
     */
    name: any;
    /**
     *
     * @type {string}
     * @memberof Project
     */
    description: any;
    /**
     *
     * @type {string}
     * @memberof Project
     */
    visibility: ProjectVisibilityEnum;
    /**
     *
     * @type {string}
     * @memberof Project
     */
    template: ProjectTemplateEnum;
    /**
     *
     * @type {string}
     * @memberof Project
     */
    state?: ProjectStateEnum;
    /**
     *
     * @type {string}
     * @memberof Project
     */
    owner?: any;
    /**
     *
     * @type {Array&lt;string&gt;}
     * @memberof Project
     */
    members?: any;
    /**
     *
     * @type {string}
     * @memberof Project
     */
    repoBucket?: any;
    /**
     *
     * @type {string}
     * @memberof Project
     */
    createAt?: any;
    /**
     *
     * @type {string}
     * @memberof Project
     */
    lastUpdate?: any;
}
/**
    * @export
    * @enum {string}
    */
export declare enum ProjectVisibilityEnum {
    PRIVATE = "PRIVATE",
    PUBLIC = "PUBLIC"
}
/**
    * @export
    * @enum {string}
    */
export declare enum ProjectTemplateEnum {
    GENERIC = "GENERIC"
}
/**
    * @export
    * @enum {string}
    */
export declare enum ProjectStateEnum {
    OPEN = "OPEN",
    CLOSED = "CLOSED"
}
