/**
 * Ilyde Apis
 * OpenApi interface which exposes Ilyde resources to frontends
 *
 * OpenAPI spec version: 0.2.0
 * Contact: alessiofiorentino@hopenly.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface ProjectslistQuery
 */
export interface ProjectslistQuery {
    /**
     *
     * @type {string}
     * @memberof ProjectslistQuery
     */
    visibility: ProjectslistQueryVisibilityEnum;
    /**
     *
     * @type {string}
     * @memberof ProjectslistQuery
     */
    state: ProjectslistQueryStateEnum;
}
/**
    * @export
    * @enum {string}
    */
export declare enum ProjectslistQueryVisibilityEnum {
    PRIVATE = "PRIVATE",
    PUBLIC = "PUBLIC"
}
/**
    * @export
    * @enum {string}
    */
export declare enum ProjectslistQueryStateEnum {
    OPEN = "OPEN",
    CLOSED = "CLOSED"
}
