/**
 * Ilyde Apis
 * OpenApi interface which exposes Ilyde resources to frontends
 *
 * OpenAPI spec version: 0.2.0
 * Contact: alessiofiorentino@hopenly.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface Run
 */
export interface Run {
    /**
     *
     * @type {string}
     * @memberof Run
     */
    id?: any;
    /**
     *
     * @type {WorkspaceMetadata}
     * @memberof Run
     */
    metadata: any;
    /**
     *
     * @type {string}
     * @memberof Run
     */
    state?: RunStateEnum;
    /**
     *
     * @type {RunSpec}
     * @memberof Run
     */
    spec: any;
    /**
     *
     * @type {number}
     * @memberof Run
     */
    uptime?: any;
    /**
     *
     * @type {string}
     * @memberof Run
     */
    createAt?: any;
    /**
     *
     * @type {string}
     * @memberof Run
     */
    lastUpdate?: any;
}
/**
    * @export
    * @enum {string}
    */
export declare enum RunStateEnum {
    CREATED = "CREATED",
    STARTING = "STARTING",
    RUNNING = "RUNNING",
    ABORTED = "ABORTED",
    SUCCEEDED = "SUCCEEDED",
    FAILED = "FAILED"
}
