/**
 * Ilyde Apis
 * OpenApi interface which exposes Ilyde resources to frontends
 *
 * OpenAPI spec version: 0.2.0
 * Contact: alessiofiorentino@hopenly.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface User
 */
export interface User {
    /**
     *
     * @type {string}
     * @memberof User
     */
    id?: any;
    /**
     *
     * @type {string}
     * @memberof User
     */
    username: any;
    /**
     *
     * @type {string}
     * @memberof User
     */
    firstName: any;
    /**
     *
     * @type {string}
     * @memberof User
     */
    lastName: any;
    /**
     *
     * @type {string}
     * @memberof User
     */
    email: any;
    /**
     *
     * @type {string}
     * @memberof User
     */
    password: any;
    /**
     *
     * @type {Array&lt;string&gt;}
     * @memberof User
     */
    groups?: any;
    /**
     *
     * @type {boolean}
     * @memberof User
     */
    emailVerified?: any;
    /**
     *
     * @type {boolean}
     * @memberof User
     */
    enabled?: any;
    /**
     *
     * @type {string}
     * @memberof User
     */
    createdTimestamp?: any;
}
