/**
 * Ilyde Apis
 * OpenApi interface which exposes Ilyde resources to frontends
 *
 * OpenAPI spec version: 0.2.0
 * Contact: alessiofiorentino@hopenly.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface Workspace
 */
export interface Workspace {
    /**
     *
     * @type {string}
     * @memberof Workspace
     */
    id?: any;
    /**
     *
     * @type {WorkspaceMetadata}
     * @memberof Workspace
     */
    metadata: any;
    /**
     *
     * @type {string}
     * @memberof Workspace
     */
    state?: WorkspaceStateEnum;
    /**
     *
     * @type {WorkspaceSpec}
     * @memberof Workspace
     */
    spec: any;
    /**
     *
     * @type {number}
     * @memberof Workspace
     */
    uptime?: any;
    /**
     *
     * @type {string}
     * @memberof Workspace
     */
    createAt?: any;
    /**
     *
     * @type {string}
     * @memberof Workspace
     */
    lastStart?: any;
    /**
     *
     * @type {string}
     * @memberof Workspace
     */
    lastUpdate?: any;
}
/**
    * @export
    * @enum {string}
    */
export declare enum WorkspaceStateEnum {
    CREATED = "CREATED",
    STARTING = "STARTING",
    RUNNING = "RUNNING",
    STOPPED = "STOPPED"
}
